sudo: false

language: android

android:
  components:
     - tools
     - tools
     - android-27
     - build-tools-27.0.3
     - platform-tools
     - extra-android-m2repository
     - extra-google-m2repository
     - cmake

jdk:
  - oraclejdk8

before_install:
  - echo "y" | sdkmanager "platforms;android-27"
  - echo "y" | sdkmanager "cmake;3.6.4111459"

before_script:
  # Install NDK
  - export NDK="android-ndk-r16"
  - export TERM=dumb
  - curl -L https://dl.google.com/android/repository/$NDK-linux-x86_64.zip -O
  - unzip -qo $NDK-linux-x86_64.zip
  - rm $NDK-linux-x86_64.zip
  - export ANDROID_NDK_HOME=`pwd`/$NDK
  - export LOCAL_ANDROID_NDK_HOME="$ANDROID_NDK_HOME"
  - export LOCAL_ANDROID_NDK_HOST_PLATFORM="linux-x86_64"
  - export PATH=$PATH:${ANDROID_NDK_HOME}

script:
  - ./gradlew clean lintDebug testDebug assDebug

notifications:
  email:
    on_success: never
    on_failure: always

before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/

cache:
  directories:
     - $HOME/.gradle/caches/
     - $HOME/.gradle/wrapper/
     - $HOME/.android/build-cache
